### ISSUE TITLE
Raise ArgumentError when using activerecord-cause 0.6.0 and Rails 5.0.7

### ISSUE THREAD

**Issue by siman-man** [joker1007/activerecord-cause#11]
`activerecord-cause` calls `type_casted_binds` method with two arguments.

https://github.com/joker1007/activerecord-cause/blob/v0.6.0/lib/activerecord/cause.rb#L146

```ruby
casted_params = type_casted_binds(payload[:binds], payload[:type_casted_binds])
```

but, in Rails 5.0.7, this [PR (rails/rails#29623)](https://github.com/rails/rails/pull/29623) changed arity of `ActiveRecord::LogSubscriber#type_casted_binds` changed from 2 to 1.

Therefore ArgumentError is occurring.

```
Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 2, expected 1)
```

**Comment by joker1007** [comment]
Thanks !!
I release v0.7.0 which supports rails-5.0.7
